name: Python Linting

on:
  push:
    branches: [ main ]
    paths:
      - 'app/**/*.py'
  pull_request:
    branches: [ main ]
    paths:
      - 'app/**/*.py'

jobs:
  flake8-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8' # Specify the Python version you're using

    - name: Install flake8
      run: python -m pip install flake8

    - name: Run flake8
      run: flake8 app/ --count --select=E9,F63,F7,F82 --show-source --statistics
      # The above command will run flake8 on the app/ directory, focusing on critical errors.
      # You can adjust the flake8 options as per your project requirements.